### ISSUE TITLE
Output is very noisy if connect fails

### ISSUE THREAD

**Issue by tatref** [leeclemens/check_elasticsearch_snapshot#10]
Example:

```
(venv) [user@host ~]$ ./check_elasticsearch_snapshot -m http -s localhost -p 920 -w 5m -c 20m -r repo01
./check_elasticsearch_snapshot: Unhandled exception <class 'requests.exceptions.ConnectionError'>
HTTPConnectionPool(host='localhost', port=920): Max retries exceeded with url: /_snapshot/repo01/_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f941df2e320>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f941df2e320>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/venv/lib64/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/user/venv/lib64/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=920): Max retries exceeded with url: /_snapshot/repo01/_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f941df2e320>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./check_elasticsearch_snapshot", line 251, in <module>
    run(parse_args())
  File "./check_elasticsearch_snapshot", line 124, in run
    now)
  File "./check_elasticsearch_snapshot", line 90, in check_repository_status
    '_snapshot/{}/_all'.format(repository))['snapshots']:
  File "./check_elasticsearch_snapshot", line 65, in query
    auth=(args.username, args.password))
  File "/home/user/venv/lib64/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/user/venv/lib64/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/venv/lib64/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/venv/lib64/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/venv/lib64/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=920): Max retries exceeded with url: /_snapshot/repo01/_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f941df2e320>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by leeclemens** [comment]
This is great feedback, thank you! Can you reproduce the error with your patch and provide it here to compare the output?

**Comment by tatref** [comment]
```
Request failed: HTTPConnectionPool(host='localhost', port=920): Max retries exceeded with url: /_snapshot/repo01/_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f60327898>: Failed to establish a new connection: [Errno 111] Connection refused'))

```
